sudo: required
services:
  - docker

before_install:
  - docker build -t rauleddie18/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rauleddie18/react-test npm test -- --coverage

after_success:
  - docker build -t rauleddie18/multi-client ./client
  - docker build -t rauleddie18/multi-nginx ./nginx
  - docker build -t rauleddie18/multi-server ./server
  - docker build -t rauleddie18/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rauleddie18/multi-client
  - docker push rauleddie18/multi-nginx
  - docker push rauleddie18/mutli-server
  - docker push rauleddie18/mutli-worker